
server:
  port: 8082
spring:
  application:
    name: cardHolder-app

  sql:
    init:
      continue-on-error: true
  cloud:
    open-feign:
      client:
        config:
          apiClient:
            connectTimeout: 3000
            readTimeout: 500
            loggerLevel: BASIC
  datasource:
    url: jdbc:postgresql://localhost:5434/postgres
    username: admin
    password: root
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 0
      maximum-pool-size: 15
      connection-timeout: 3000
      idle-timeout: 300000
      max-lifetime: 600000
      initialization-fail-timeout: -1
      validation-timeout: 1000

  jpa:
    generate-ddl: false
    show-sql: true

